### ISSUE TITLE
Unable to install on Mac M1

### ISSUE THREAD

**Issue by saridsa1** [shoutsid/townhall#54]
When I build the docker container I get this error, with docker. 
34.01      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 779.4 kB/s eta 0:00:00
34.18 ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
34.18 ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu12>=12.2.5.6 (from versions: 0.0.1.dev5)
34.18 ERROR: No matching distribution found for nvidia-cublas-cu12>=12.2.5.6
34.40
34.40 [notice] A new release of pip is available: 23.1.2 -> 23.3.1
34.40 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:14
--------------------
  12 |
  13 |     # Install any needed packages specified in requirements.txt
  14 | >>> RUN pip install --no-cache-dir -r requirements.txt
  15 |
  16 |     # Make port 80 available to the world outside this container
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1

Please help.

**Comment by shoutsid** [comment]
I'm fixing this right now, will merge a PR within the coming hours. The work is currently on being worked on as part of https://github.com/shoutsid/townhall/pull/56 
As this same issue was breaking Github Codespaces. 

Thanks for trying this out!

**Comment by shoutsid** [comment]
For mac, I need to also write a specific README. Or use a seperate requirements.txt file. 

Currently within the requirements.txt, you need to uncomment the following if you wish to use the llama/gpt2 integration. 

```
# Used for Mac's Metal GPU support
# pyobjc-framework-Metal
# pyobjc-framework-Cocoa
# pyobjc-framework-libdispatch
```

Also append `METAL=1` to any command, or export it to your env.

**Comment by shoutsid** [comment]
separate draft PR that should fix this issue: https://github.com/shoutsid/townhall/pull/57

**Comment by shoutsid** [comment]
Hi @saridsa1,

Thank you for bringing this issue to our attention. We've successfully resolved the Docker build error related to Python package dependencies that you reported in Issue #54.

To incorporate these fixes, please perform a `git pull` on the main branch with the following commands:

```bash
git checkout main
git pull origin main
```

After pulling the latest changes, try rebuilding the Docker container. This should resolve the issues you were encountering.

Feel free to reopen the issue if you run into any further problems or have additional questions.

Best regards,
@shoutsid
